//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSContracts.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMSContracts.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment does not exist.
        /// </summary>
        public static string appointmentDoesnotExist {
            get {
                return ResourceManager.GetString("appointmentDoesnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email does not exist.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is used before.
        /// </summary>
        public static string EmailUsedBefore {
            get {
                return ResourceManager.GetString("EmailUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Appointment is used in MedicalRecord You can not delete it.
        /// </summary>
        public static string invalidAppointment {
            get {
                return ResourceManager.GetString("invalidAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment does not exist.
        /// </summary>
        public static string MedicalRecordDoesnotExist {
            get {
                return ResourceManager.GetString("MedicalRecordDoesnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Medical Record is deleted.
        /// </summary>
        public static string MRDeleted {
            get {
                return ResourceManager.GetString("MRDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must upload a file or provide an image path..
        /// </summary>
        public static string MustUpload {
            get {
                return ResourceManager.GetString("MustUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patient does not has this appointment.
        /// </summary>
        public static string patientDoesnotHasThisAppointment {
            get {
                return ResourceManager.GetString("patientDoesnotHasThisAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role doesn&apos;t exist.
        /// </summary>
        public static string RoleDoesnotExist {
            get {
                return ResourceManager.GetString("RoleDoesnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role is already exist.
        /// </summary>
        public static string RoleIsExist {
            get {
                return ResourceManager.GetString("RoleIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UserName or Email is used before.
        /// </summary>
        public static string UsedBefore {
            get {
                return ResourceManager.GetString("UsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user doesn&apos;t exist.
        /// </summary>
        public static string UseDoesnotExist {
            get {
                return ResourceManager.GetString("UseDoesnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user name is used before.
        /// </summary>
        public static string UserNameUsedBefore {
            get {
                return ResourceManager.GetString("UserNameUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided image path must be a valid URL..
        /// </summary>
        public static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is not Correct.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
